# docker-compose.yml
version: "3.9"

services:
  app:
    build: .
    container_name: threejs-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /mnt/1EXT8T/HOME/janick.koder/DevContainer_Share/educiDev:/usr/src/app/shared
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - cftunnel

networks:
  cftunnel:
    external: true
